config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :owners, :controllers => { registrations: 'registrations' }

  root "welcome#index"

  resources :restaurants do
    resources :reservations
  end

  resources :restaurants do
    put :favorite, on: :member
  end

  get "owners/:owner_id/dashboard", to: "owners#dashboard", as: "owner_dashboard"
  get "users/:user_id/dashboard", to: "users#dashboard", as: "user_dashboard"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :name, presence: true, length: {minimum: 2}
  has_many :restaurants
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user, optional: true

  scope :for_user, -> (user) { where(user_id: user.id) }
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true, length: {minimum: 2}
  validates :address, presence: true, length: {minimum: 10}
  validates :phone_number, presence: true, length: {minimum: 10}
  validates :food_type, presence: true, length: {minimum: 2}

  geocoded_by :address
  after_validation :geocode

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  belongs_to :owner
  has_many :reservations
  has_many :favorites
  has_many :favoritors, source: :user, through: :favorites

  def google_map(center)
    "https://maps.googleapis.com/maps/api/staticmap?center=#{center}&size=300x300&zoom=17"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :reservations
  has_many :favorites
  has_many :favorite_restaurants, source: :resturant, through: :favorites

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :find_owner
  before_action :check_owner

  def dashboard
    @restaurants = @owner.restaurants
  end

  private

  def find_owner
    @owner = Owner.find(params[:owner_id])
  end

  def check_owner
    redirect_to(root_path, notice: 'This ain\'t yours') if @owner != current_owner
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:owner).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:owner).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  before_action :find_restaurant, only: [:index, :new, :create, :destroy]

  def new
    
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.restaurant_id = @restaurant.id
    @reservation.user_id = current_user.try(:id)

    if @reservation.save
      OwnerMailer.new_reservation_email(@reservation).deliver
      redirect_to @restaurant
    else
      render 'new'
    end
  end

  def show
  end

  def index
    @reservations = @restaurant.reservations
  end

  def edit
  end

  def update
    if @reservation.update(reservation_params)
      redirect_to @reservation
    else
      render 'edit'
    end
  end

  def destroy
    @reservation.destroy
    redirect_to @restaurant
  end

  private

  def reservation_params
    params.require(:reservation).permit(:restaurant_id, :guest_name, :notes, :event_on, :event_time, :user_id)
  end

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :favorite]
  before_action :check_owner, only: [:edit, :update, :destroy]
  before_action :authenticate_owner!, only: [:edit, :update, :new, :create]

  def new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.owner = current_owner

    if @restaurant.save
      redirect_to @restaurant
    else
      render 'new'
    end
  end

  def show
  end

  def index
    @restaurants = Restaurant.all
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant.destroy
    render 'index'
  end

  def favorite
    if params[:type] == "favorite"
      Favorite.create(restaurant: @restaurant, user: current_user)
      redirect_to @restaurant, notice: "Favorited!"
    else
      @restaurant.favoritors.delete(current_user)
      redirect_to @restaurant, notice: "Unfavorited :c"
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :food_type, :phone_number, :photo)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def check_owner
    redirect_to(restaurants_url, notice: 'This ain\'t yours') if @restaurant.owner != current_owner
  end
end

app/controllers/users/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user
  before_action :check_user

  def dashboard
    @reservations = Reservation.for_user(@user)
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end

  def check_user
    redirect_to(root_path, notice: 'This ain\'t yours') if @user != current_user   
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/owners/dashboard.html.erb
<h1>Your Restaurants</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Phone Number</th>
    <th>Food Type</th>
    <th>Logo</th>
    <th colspan="2"></th>
  </tr>

  <% @restaurants.each do |r| %>
    <tr>
      <td><%= r.name %></td>
      <td><%= r.address %></td>
      <td><%= r.phone_number %></td>
      <td><%= r.food_type %></td>
      <td><%= image_tag r.photo.url(:thumb) %></td>
      <td><%= link_to 'View', restaurant_path(r.id), class: "btn btn-primary" %></td>
      <td><%= link_to 'Edit', edit_restaurant_path(r.id), class: "btn btn-primary" %></td>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to 'Create New Restaurant', new_restaurant_path, class: "btn btn-primary" %>
</p>

app/views/reservations/index.html.erb
<h1>All Reservations for <%= @restaurant.name %></h1>

<table class="table">
  <tr>
    <th>Guest Name</th>
    <th>Event Date</th>
    <th>Event Time</th>
    <th>Guest's Note</th>
    <th colspan="2"></th>
  </tr>

  <% @reservations.each do |res| %>
    <tr>
      <td><%= res.guest_name %></td>
      <td><%= res.event_on %></td>
      <td><%= res.event_time %></td>
      <td><%= res.notes %></td>
      <td><%= link_to "View", restaurant_reservation_path(@restaurant.id, res.id), class: "btn btn-primary" %></td>
      <td><%= link_to "Delete", [@restaurant, res], method: :delete, class: "btn btn-primary" %></td>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to 'Create New Reservation', new_restaurant_reservation_path, class: "btn btn-primary" %>
</p>

app/views/reservations/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h1>New Reservation for <%= @restaurant.name %></h1>
    </div>
  </div>
  <div class="panel-body">
    <%= form_for :reservation, url: restaurant_reservations_path, html: { multipart: true } do |f| %>
      <div class="form-group">
        <p>
          <%= f.label :guest_name %>
          <%= f.text_field :guest_name, class: "form-control" %>
        </p>
      </div>

      <div class="form-group">
        <p>
          <%= f.label :event_on %>
          <%= f.text_field :event_on, class: "form-control" %>
        </p>
      </div>

      <div class="form-group">
        <p>
          <%= f.label :event_time %>
          <%= f.text_field :event_time, class: "form-control" %>
        </p>
      </div>

      <div class="form-group">
        <p>
          <%= f.label :notes %>
          <%= f.text_area :notes, class: "form-control" %>
        </p>
      </div>

      <div class="form-group">
        <p>
          <%= f.submit "Save Reservation", class: "btn btn-primary" %>
        </p>
      </div>
    <% end %>
  </div>

  <div class="panel-footer">
    <p>
      <%= link_to 'View All', restaurant_reservations_path %>
    </p>
  </div>
</div>

app/views/reservations/show.html.erb
<h1>Reservation # <%= @reservation.id %></h1>

<table class="table">
  <tr>
    <th>Guest Name</th>
    <th>Event Date</th>
    <th>Event Time</th>
    <th>Guest's Note</th>
  </tr>

  <tr>
    <td><%= @reservation.guest_name %></td>
    <td><%= @reservation.event_on %></td>
    <td><%= @reservation.event_time %></td>
    <td><%= @reservation.notes %></td>
  </tr>
</table>

<p>
  <%= link_to 'View All Reservations', restaurant_reservations_path, class: "btn btn-primary" %>
</p>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant #<% @restaurant.id %></h1>

<%= form_for @restaurant, html: { multipart: true } do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </p>

  <p>
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </p>

  <p>
    <%= f.label :food_type %>
    <%= f.text_field :food_type %>
  </p>

  <p>
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Phone Number</th>
    <th>Food Type</th>
    <th>Logo</th>
    <th colspan="2"></th>
  </tr>

  <% @restaurants.each do |r| %>
    <tr>
      <td><%= r.name %></td>
      <td><%= r.address %></td>
      <td><%= r.phone_number %></td>
      <td><%= r.food_type %></td>
      <td><%= image_tag r.photo.url(:thumb) %></td>
      <td><%= link_to 'View', restaurant_path(r.id), class: "btn btn-primary" %></td>
      <td>
        <% if current_owner == r.owner %>
          <%= link_to 'Edit', edit_restaurant_path(r.id), class: "btn btn-primary" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<% if current_owner.present? %>
  <p>
    <%= link_to 'Create New Restaurant', new_restaurant_path, class: "btn btn-primary" %>
  </p>
<% end %>

app/views/restaurants/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h1>New Restaurant</h1>
    </div>
  </div>
  <div class="panel-body">
    <%= form_for :restaurant, url: restaurants_path, html: { multipart: true } do |f| %>
      <div class="form-group">
        <p>
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </p>
      </div>

      <div class="form-group">
        <p>
          <%= f.label :address %>
          <%= f.text_field :address, class: "form-control" %>
        </p>
      </div>

      <div class="form-group">
        <p>
          <%= f.label :phone_number %>
          <%= f.text_field :phone_number, class: "form-control" %>
        </p>
      </div>

      <div class="form-group">
        <p>
          <%= f.label :food_type %>
          <%= f.text_field :food_type, class: "form-control" %>
        </p>
      </div>

      <div class="form-group">
        <p>
          <%= f.label :photo %>
          <%= f.file_field :photo %>
        </p>
      </div>

      <div class="form-group">
        <p>
          <%= f.submit "Save Restaurant", class: "btn btn-primary" %>
        </p>
      </div>
    <% end %>
  </div>

  <div class="panel-footer">
    <p>
      <%= link_to 'View All', restaurants_path %>
    </p>
  </div> 
</div>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<table class="table">
  <tr>
    <th>Owner</th>
    <th>Address</th>
    <th>Phone Number</th>
    <th>Food Type</th>
    <th>Logo</th>
    <th>Location</th>
    <th></th>
  </tr>

  <tr>
    <td><%= @restaurant.owner.name %></td>
    <td><%= @restaurant.address %></td>
    <td><%= @restaurant.phone_number %></td>
    <td><%= @restaurant.food_type %></td>
    <td><%= image_tag @restaurant.photo.url(:thumb) %></td>
    <td><%= image_tag @restaurant.google_map(center: @restaurant.address) %></td>
    <td>
      <% if current_owner == @restaurant.owner %>
        <%= link_to "View reservations", restaurant_reservations_path(@restaurant), class: "btn btn-primary" %>
      <% else %>
        <%= link_to "Make new reservation", new_restaurant_reservation_path(@restaurant), class: "btn btn-primary" %>
      <% end %>
    </td>
</table>

<p>
  <%= link_to 'Back to All Restaurants', restaurants_path, class: "btn btn-primary" %>
</p>

<% if current_user.present? %>
  <p>
    <% if Favorite.exists?(restaurant: @restaurant, user: current_user) %>
      <%= link_to "Unfavorite", favorite_restaurant_path(@restaurant, type: "unfavorite"), method: :put, remote: true, class: "btn btn-primary" %>
    <% else %>
      <%= link_to "Favorite", favorite_restaurant_path(@restaurant, type: "favorite"), method: :put, remote: true, class: "btn btn-primary" %>
    <% end %>
  </p>
<% end %>