config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :owners, :controllers => { registrations: 'registrations' }

  root "welcome#index"

  resources :restaurants do
    resources :reservations
  end

  resources :restaurants do
    put :favorite, on: :member
  end

  get "owners/:owner_id/dashboard", to: "owners#dashboard", as: "owner_dashboard"
  get "users/:user_id/dashboard", to: "users#dashboard", as: "user_dashboard"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :name, presence: true, length: {minimum: 2}
  has_many :restaurants
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user, optional: true

  scope :for_user, -> (user) { where(user_id: user.id) }
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true, length: {minimum: 2}
  validates :address, presence: true, length: {minimum: 10}
  validates :phone_number, presence: true, length: {minimum: 10}
  validates :food_type, presence: true, length: {minimum: 2}

  geocoded_by :address
  after_validation :geocode

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  belongs_to :owner
  has_many :reservations
  has_many :favorites
  has_many :favoritors, source: :user, through: :favorites

  def google_map(center)
    "https://maps.googleapis.com/maps/api/staticmap?center=#{center}&size=300x300&zoom=17"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :reservations
  has_many :favorites
  has_many :favorite_restaurants, source: :resturant, through: :favorites

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :find_owner
  before_action :check_owner

  def dashboard
    @restaurants = @owner.restaurants
  end

  private

  def find_owner
    @owner = Owner.find(params[:owner_id])
  end

  def check_owner
    redirect_to(root_path, notice: 'This ain\'t yours') if @owner != current_owner
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :favorite]
  before_action :check_owner, only: [:edit, :update, :destroy]
  before_action :authenticate_owner!, only: [:edit, :update, :new, :create]

  def new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.owner = current_owner

    if @restaurant.save
      redirect_to @restaurant
    else
      render 'new'
    end
  end

  def show
  end

  def index
    @restaurants = Restaurant.all
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant.destroy
    render 'index'
  end

  def favorite
    if params[:type] == "favorite"
      Favorite.create(restaurant: @restaurant, user: current_user)
      redirect_to @restaurant, notice: "Favorited!"
    else
      @restaurant.favoritors.delete(current_user)
      redirect_to @restaurant, notice: "Unfavorited :c"
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :food_type, :phone_number, :photo)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def check_owner
    redirect_to(restaurants_url, notice: 'This ain\'t yours') if @restaurant.owner != current_owner
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Reservester", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>

        <% if owner_signed_in? %>
          <li><%= link_to "Account Settings", edit_owner_registration_path %></li>
          <li><%= link_to "Log out", destroy_owner_session_path, method: :delete %></li>
        <% elsif user_signed_in? %>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reservester</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    <div class="container">
      <%= render "layouts/header" %>

      <%= yield %>
    </div>
  </body>
</html>